[package]
name = "aoc2021"
version = "0.1.0"
authors = [ "Adamaq01 <adamthibert01@gmail.com>" ]
license = "MIT"
edition = "2021"

[dependencies]
aoc-proc-macros = { path = "proc-macros" }
clap = "3.0.0-beta.5"
dotenv = "0.15"
reqwest = { version = "0.11", features = [ "blocking" ] }
